- hosts: terraform-ansible
  tasks:
    - name: Intalling python3, virtualenv
      become: yes
      apt:
        pkg:
          - python3
          - python3-pip
          - virtualenv
        update_cache: yes