- hosts: terraform-ansible
  tasks:
    - name: Intalling python3, virtualenv
      become: yes
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
    - name: Install dependencies with pip Django and Django REST framework
      become: yes
      pip:
        virtualenv: /home/ubuntu/venv
        name:
          - django
          - djangorestframework
    - name: Start Django server
      shell: |
        . /home/ubuntu/venv/bin/activate
        django-admin startproject mysite /home/ubuntu/
    - name: Change hosts to settings.py
      become: yes
      lineinfile:
        path: /home/ubuntu/mysite/settings.py
        regexp: '^ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'    